### PR TITLE
Exclude torrents uploaded by an user from their "Snatched" list on profile page

### PR DESCRIPTION
**Pull request by hluup**
As per forum thread #9210

### CODE REVIEW

**Comment by ligh7s** [comment]
This is improperly implemented. A check needs to go here https://github.com/ApolloRIP/Gazelle/blob/master/sections/torrents/download.php#L156 as well, since the query you altered is only used when the cache key doesn't exist.

Essentially, add `&& $UploaderID != $UserID` to line 157.

**Comment by hluup** [comment]
Mm, It makes more sense to exclude those before caching. I don't see a reason to cache results that we aren't going to display anyways. And wouldn't your solution display less than  snatched torrents if some of the queried ones are uploaded by the displayed user?

**Comment by ligh7s** [comment]
Sorry, I don't understand. The cache key for recent snatches never expires, aka it is kept in memory and only resets when memcache is restarted. When a user downloads a .torrent file, a function on `sections/torrents/download.php` alters the array associated with the existing cache key. The query you altered is almost never ran.  

I'm not sure what you mean by my solution displaying less than snatched torrents either.

**Comment by hluup** [comment]
Aah sorry, now I see it yeah. Didn't read the code carefully enough.

Tbh it's quite confusing if that this cache value is altered in two places. I can see the performance gain that it gives, but it seems more correct to just invalidate the recent_snatches case in the event of downloading a new torrent and let the query deal with it from there.

I'll look at it again later.

**Pull request closed without merging**
