### PR TITLE
(Update) Adopt PHP PSR-2 Coding Style + Adopt  PHP Short Array Syntax + General Cleanup + Remove/Replace Depreciations

### PR DESCRIPTION
**Pull request by HDVinnie**
- automated by php-shift
- untested

### CODE REVIEW

**Comment by welp-ops** [comment]
You are switching from one well-defined style guide to another well-defined style guide and pretending that counts as modernizing the codebase. Nothing gained, nothing lost. Well, except that developers will have to get used to the new style guide, we have to check that 25k lines of code are clean, and any unmerged branches will become in conflict. -1 from me.

I do not speak for IIM or any other staff.

**Comment by HDVinnie** [comment]
Its called keeping up with todays standards but ok. I don't see how I'm pretending it modernizing the codebase. It is. Maybe not in functionality but in standards.

**Comment by itismadness** [comment]
I very much agree with the spirit of this PR. These are good standards (spaces over tabs, one class per file, short array syntax over long, etc.) and I'd very much like to see them folded into Gazelle, and have been part of our internal roadmap that we've been working on establishing into set guidelines to be released here.

Having said that, we're not going to merge something like this when it's not done by a core Orpheus developer. This is too many lines and files affected at once that is just going to place an overarching burden on us to review it, merge it, deal with all other merge conflicts, etc. Honestly, for this kind of change and cleanup, it's best to leave it to us as we can do it when it's appropriate, in batches, etc. that doesn't conflict with any of the work we're doing or within other PRs on Github. To some extent, for stuff like "remove all closing tags" or "convert all to short array syntax", it's probably better to do this as we touch files and improve them in other ways than just batch change it as well.

Thank you though for your interest in improving this project.

**Comment by HDVinnie** [comment]
@itismadness not a problem.....was worth a shot.

**Pull request closed without merging**
