### PR TITLE
 Prevent execution of composer failed but docker image built successfully

### PR DESCRIPTION
**Pull request by soleil0-0**
Add "set -e;" to prevent execution of composer failed but docker image built successfully

### CODE REVIEW

**Comment by ops-webhead** [comment]
This is not desired behavior, as composer deps can always be installed after the fact.

In fact, in the next code dump you will see this step moved from build-time to run-time as part of the entrypoint script.

**Comment by soleil0-0** [comment]
> This is not desired behavior, as composer deps can always be installed after the fact.
> 
> In fact, in the next code dump you will see this step moved from build-time to run-time as part of the entrypoint script.

You can't confirm docker image is 100% usable while we may encounter this situation "composer install failed (Accidental network problem), but yarn is ok". 

"docker build" must be failed when "composer install" failed.

**Comment by ops-webhead** [comment]
Composer failing to install is not a critical part of the container itself. Yes, it is required for Gazelle to run, but there are other ways to do it aside from having docker do it in the build step.

Again -- this code in the dockerfile is already out of date so it will not be patched. Wait until we are able to make another code dump and you will see that the `composer install` has been moved, making this irrelevant.

**Comment by soleil0-0** [comment]
> Composer failing to install is not a critical part of the container itself. Yes, it is required for Gazelle to run, but there are other ways to do it aside from having docker do it in the build step.
> 
> Again -- this code in the dockerfile is already out of date so it will not be patched. Wait until we are able to make another code dump and you will see that the `composer install` has been moved, making this irrelevant.

Thx, I see. There is no need to fix current version Dockerfile. Just wait next code dump.

Can you close ths pull request? I don't have right to close it.

**Comment by garrettw** [comment]
@soleil0-0 check out the code now :)

**Pull request closed without merging**
